export const FETCH_MOVIES_START = "FETCH_MOVIES_START";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_ERROR = "FETCH_MOVIES_ERROR";

export const SAVE_FAV_MOVIE = "SAVE_FAV_MOVIE";
export const SAVE_FAV_MOVIE_START = "SAVE_FAV_MOVIE_START";
export const SAVE_FAV_MOVIE_SUCCESS = "SAVE_FAV_MOVIE_SUCCESS";
export const SAVE_FAV_MOVIE_ERROR = "SAVE_FAV_MOVIE_ERROR";

export const SAVE_FAV_MOVIE_LIST = "SAVE_FAV_MOVIE_LIST";

export const REMOVE_FAV_MOVIE = "REMOVE_FAV_MOVIE";
export const REMOVE_FAV_MOVIE_START = "REMOVE_FAV_MOVIE_START";
export const REMOVE_FAV_MOVIE_SUCCESS = "REMOVE_FAV_MOVIE_SUCCESS";
export const REMOVE_FAV_MOVIE_ERROR = "REMOVE_FAV_MOVIE_ERROR";

export const LOAD_MORE_MOVIES = "LOAD_MORE_MOVIES";
export const LOAD_MORE_MOVIES_SUCCESS = "LOAD_MORE_MOVIES_SUCCESS";
export const LOAD_MORE_MOVIES_FAIL = "LOAD_MORE_MOVIES_FAIL";
