export const FETCH_MOVIES_START = "FETCH_MOVIES_START";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_ERROR = "FETCH_MOVIES_ERROR";

export const SAVE_FAV_MOVIE = "SAVE_FAV_MOVIE";
export const REMOVE_FAV_MOVIE = "REMOVE_FAV_MOVIE";
